package com.jobservice.exception;

public enum ErrorCode {
    VALIDATION_FAILED,
    MALFORMED_REQUEST,
    EMAIL_ALREADY_EXISTS,
    USERNAME_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    DATA_INTEGRITY_VIOLATION,
    INTERNAL_SERVER_ERROR
}
