global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: job-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          service: job-service

  - job_name: watcher-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          service: watcher-service

  - job_name: executor-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8082"]
        labels:
          service: executor-service
